kind: pipeline
type: docker
name: default

steps:
- name: backend
  image: golang
  commands:
  - cd src
  - go build main.go
  - go test

- name: frontend
  image: node:12-alpine
  commands:
  - cd frontend
  - yarn install
  - yarn build
