kind: pipeline
type: docker
name: Builds features except main

steps:
- name: Build C# Project
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - cd csharpProject
  - dotnet build
  - dotnet test

- name: backend
  image: golang
  commands:
  - cd src
  - go build main.go
  - go test
when:
  branch:
  - feature/*
  event:
  - push

---
kind: pipeline
type: docker
name: Build main and publish docker images

steps:
- name: Build C# Project
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - cd csharpProject
  - dotnet build
  - dotnet test

- name: backend
  image: golang
  commands:
  - cd src
  - go build main.go
  - go test

- name: Publish Go Project
  image: plugins/docker
  settings:
    username: alexsandre
    password:
      from_secret: DockerHubToken
    repo: alexsandre/drone_go_project
    tags:
    - latest

trigger:
  branch:
  - main
  event:
  - promote
  - push
  target:
  - production


---
kind: pipeline
type: docker
name: Build PRs

steps:
- name: Build C# Project
  image: mcr.microsoft.com/dotnet/sdk:5.0
  commands:
  - cd csharpProject
  - dotnet build
  - dotnet test

- name: backend
  image: golang
  commands:
  - cd src
  - go build main.go
  - go test

trigger:
  event:
  - pull_request